**PREPROCESSING**

In [520]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import chi2_contingency
from scipy.stats import f_oneway
from imblearn.over_sampling import SMOTE

from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import TargetEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [496]:
df = pd.read_csv("C:\\Users\\Abhishek k\\OneDrive\\Documents\\projects\\mini project ml\\Dataset\\dataset_final1.csv")

In [497]:
df.tail()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,Away Team Score Penalties,Result,Home Team Win,Away Team Win,Draw,Home Team FIFA Rank,Away Team FIFA Rank,Year,Home Team Squad Value (€M),Away Team Squad Value (€M)
959,960,WC-2022,2022 FIFA World Cup,M-2022-60,England v France,England,France,quarter-finals,not applicable,0,...,0,away team win,0,1,0,5.0,3.0,2022,1090.0,1160.0
960,961,WC-2022,2022 FIFA World Cup,M-2022-61,Argentina v Croatia,Argentina,Croatia,semi-finals,not applicable,0,...,0,home team win,1,0,0,2.0,7.0,2022,920.0,325.0
961,962,WC-2022,2022 FIFA World Cup,M-2022-62,France v Morocco,France,Morocco,semi-finals,not applicable,0,...,0,home team win,1,0,0,3.0,11.0,2022,1160.0,310.0
962,963,WC-2022,2022 FIFA World Cup,M-2022-63,Croatia v Morocco,Croatia,Morocco,third-place match,not applicable,0,...,0,home team win,1,0,0,7.0,11.0,2022,325.0,310.0
963,964,WC-2022,2022 FIFA World Cup,M-2022-64,Argentina v France,Argentina,France,final,not applicable,0,...,2,home team win,1,0,0,2.0,3.0,2022,920.0,1160.0

In [498]:
df.shape

(964, 44)

In [499]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 44 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Key Id                      964 non-null    int64
 1   Tournament Id               964 non-null    object
 2   tournament Name             964 non-null    object
 3   Match Id                    964 non-null    object
 4   Match Name                  964 non-null    object
 5   Team 1                      964 non-null    object
 6   Team 2                      964 non-null    object
 7   Stage Name                  964 non-null    object
 8   Group Name                  964 non-null    object
 9   Group Stage                 964 non-null    int64
 10  Knockout Stage              964 non-null    int64
 11  Replayed                    964 non-null    int64
 12  Replay                      964 non-null    int64
 13  Match Date                  964 non-null    object
 14  Match Time                  964 non-null    object
 15  Stadium Id                  964 non-null    object
 16  Stadium Name                964 non-null    object
 17  City Name                   964 non-null    object
 18  Country Name                964 non-null    object
 19  Home Team Id                964 non-null    object
 20  Home Team Name              964 non-null    object
 21  Home Team Code              964 non-null    object
 22  Away Team Id                964 non-null    object
 23  Away Team Name              964 non-null    object
 24  Away Team Code              964 non-null    object
 25  Score                       964 non-null    object
 26  Home Team Score             964 non-null    int64
 27  Away Team Score             964 non-null    int64
 28  Home Team Score Margin      964 non-null    int64
 29  Away Team Score Margin      964 non-null    int64
 30  Extra Time                  964 non-null    int64
 31  Penalty Shootout            964 non-null    int64
 32  Score Penalties             964 non-null    object
 33  Home Team Score Penalties   964 non-null    int64
 34  Away Team Score Penalties   964 non-null    int64
 35  Result                      964 non-null    object
 36  Home Team Win               964 non-null    int64
 37  Away Team Win               964 non-null    int64
 38  Draw                        964 non-null    int64
 39  Home Team FIFA Rank         964 non-null    float64
 40  Away Team FIFA Rank         964 non-null    float64
 41  Year                        964 non-null    int64
 42  Home Team Squad Value (€M)  964 non-null    float64
 43  Away Team Squad Value (€M)  964 non-null    float64
dtypes: float64(4), int64(17), object(23)
memory usage: 331.5+ KB

In [500]:
df.describe()

,Key Id,Group Stage,Knockout Stage,Replayed,Replay,Home Team Score,Away Team Score,Home Team Score Margin,Away Team Score Margin,Extra Time,...,Home Team Score Penalties,Away Team Score Penalties,Home Team Win,Away Team Win,Draw,Home Team FIFA Rank,Away Team FIFA Rank,Year,Home Team Squad Value (€M),Away Team Squad Value (€M)
count,964.00000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,...,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000
mean,482.50000,0.744813,0.255187,0.004149,0.004149,1.766598,1.054979,0.711618,-0.711618,0.075726,...,0.121369,0.108921,0.565353,0.248963,0.185685,12.942946,17.575726,1989.244813,163.653734,121.178527
std,278.42713,0.436192,0.436192,0.064315,0.064315,1.601040,1.071720,1.925893,1.925893,0.264697,...,0.665731,0.600764,0.495968,0.432637,0.389054,15.123166,15.648710,24.014409,244.252693,204.221371
min,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-7.000000,-9.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1930.000000,0.400000,0.300000
25%,241.75000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,-2.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,6.000000,1974.000000,8.000000,5.000000
50%,482.50000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,-1.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,7.000000,13.000000,1994.000000,41.000000,35.000000
75%,723.25000,1.000000,1.000000,0.000000,0.000000,3.000000,2.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,16.000000,25.000000,2010.000000,210.000000,125.000000
max,964.00000,1.000000,1.000000,1.000000,1.000000,10.000000,7.000000,9.000000,7.000000,1.000000,...,5.000000,5.000000,1.000000,1.000000,1.000000,105.000000,105.000000,2022.000000,1160.000000,1160.000000

In [501]:
df.isna().sum()

Key Id                        0
Tournament Id                 0
tournament Name               0
Match Id                      0
Match Name                    0
Team 1                        0
Team 2                        0
Stage Name                    0
Group Name                    0
Group Stage                   0
Knockout Stage                0
Replayed                      0
Replay                        0
Match Date                    0
Match Time                    0
Stadium Id                    0
Stadium Name                  0
City Name                     0
Country Name                  0
Home Team Id                  0
Home Team Name                0
Home Team Code                0
Away Team Id                  0
Away Team Name                0
Away Team Code                0
Score                         0
Home Team Score               0
Away Team Score               0
Home Team Score Margin        0
Away Team Score Margin        0
Extra Time                    0
Penalty Shootout              0
Score Penalties               0
Home Team Score Penalties     0
Away Team Score Penalties     0
Result                        0
Home Team Win                 0
Away Team Win                 0
Draw                          0
Home Team FIFA Rank           0
Away Team FIFA Rank           0
Year                          0
Home Team Squad Value (€M)    0
Away Team Squad Value (€M)    0
dtype: int64

In [502]:
df.columns

Index(['Key Id', 'Tournament Id', 'tournament Name', 'Match Id', 'Match Name',
       'Team 1', 'Team 2', 'Stage Name', 'Group Name', 'Group Stage',
       'Knockout Stage', 'Replayed', 'Replay', 'Match Date', 'Match Time',
       'Stadium Id', 'Stadium Name', 'City Name', 'Country Name',
       'Home Team Id', 'Home Team Name', 'Home Team Code', 'Away Team Id',
       'Away Team Name', 'Away Team Code', 'Score', 'Home Team Score',
       'Away Team Score', 'Home Team Score Margin', 'Away Team Score Margin',
       'Extra Time', 'Penalty Shootout', 'Score Penalties',
       'Home Team Score Penalties', 'Away Team Score Penalties', 'Result',
       'Home Team Win', 'Away Team Win', 'Draw', 'Home Team FIFA Rank',
       'Away Team FIFA Rank', 'Year', 'Home Team Squad Value (€M)',
       'Away Team Squad Value (€M)'],
      dtype='object')

In [503]:
#df["Match Date"].dtype
df["Match Date"]=pd.to_datetime(df['Match Date'],format="mixed")
df["match_day"]=df["Match Date"].dt.day
df["match_month"]=df["Match Date"].dt.month
df["match_year"]=df["Match Date"].dt.year
df.drop("Match Date",axis=1,inplace=True)
df.head()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,Away Team Win,Draw,Home Team FIFA Rank,Away Team FIFA Rank,Year,Home Team Squad Value (€M),Away Team Squad Value (€M),match_day,match_month,match_year
0,1,WC-1930,1930 FIFA World Cup,M-1930-01,France v Mexico,France,Mexico,group stage,Group 1,1,...,0,0,6.0,20.0,1930,1.5,0.5,13,7,1930
1,2,WC-1930,1930 FIFA World Cup,M-1930-02,United States v Belgium,United States,Belgium,group stage,Group 4,1,...,0,0,10.0,8.0,1930,0.9,1.1,13,7,1930
2,3,WC-1930,1930 FIFA World Cup,M-1930-03,Yugoslavia v Brazil,Yugoslavia,Brazil,group stage,Group 2,1,...,0,0,4.0,5.0,1930,1.8,1.6,14,7,1930
3,4,WC-1930,1930 FIFA World Cup,M-1930-04,Romania v Peru,Romania,Peru,group stage,Group 3,1,...,0,0,14.0,18.0,1930,0.9,0.7,14,7,1930
4,5,WC-1930,1930 FIFA World Cup,M-1930-05,Argentina v France,Argentina,France,group stage,Group 1,1,...,0,0,2.0,6.0,1930,2.2,1.5,15,7,1930

In [504]:
df["Match Time"]=pd.to_datetime(df["Match Time"],format="mixed")
df["start_time"]=(df["Match Time"].dt.hour+(df["Match Time"].dt.minute)/60)
df.drop("Match Time",axis=1,inplace=True)

In [505]:
df["Rank difference"]=(df["Home Team FIFA Rank"]-df["Away Team FIFA Rank"])
#df["Away Rank Advantage"]=(df["Away Team FIFA Rank"]<df["Home Team FIFA Rank"]).astype(int)
df

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,Home Team FIFA Rank,Away Team FIFA Rank,Year,Home Team Squad Value (€M),Away Team Squad Value (€M),match_day,match_month,match_year,start_time,Rank difference
0,1,WC-1930,1930 FIFA World Cup,M-1930-01,France v Mexico,France,Mexico,group stage,Group 1,1,...,6.0,20.0,1930,1.5,0.5,13,7,1930,15.000000,-14.0
1,2,WC-1930,1930 FIFA World Cup,M-1930-02,United States v Belgium,United States,Belgium,group stage,Group 4,1,...,10.0,8.0,1930,0.9,1.1,13,7,1930,15.000000,2.0
2,3,WC-1930,1930 FIFA World Cup,M-1930-03,Yugoslavia v Brazil,Yugoslavia,Brazil,group stage,Group 2,1,...,4.0,5.0,1930,1.8,1.6,14,7,1930,12.750000,-1.0
3,4,WC-1930,1930 FIFA World Cup,M-1930-04,Romania v Peru,Romania,Peru,group stage,Group 3,1,...,14.0,18.0,1930,0.9,0.7,14,7,1930,14.833333,-4.0
4,5,WC-1930,1930 FIFA World Cup,M-1930-05,Argentina v France,Argentina,France,group stage,Group 1,1,...,2.0,6.0,1930,2.2,1.5,15,7,1930,16.000000,-4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,960,WC-2022,2022 FIFA World Cup,M-2022-60,England v France,England,France,quarter-finals,not applicable,0,...,5.0,3.0,2022,1090.0,1160.0,10,12,2022,22.000000,2.0
960,961,WC-2022,2022 FIFA World Cup,M-2022-61,Argentina v Croatia,Argentina,Croatia,semi-finals,not applicable,0,...,2.0,7.0,2022,920.0,325.0,13,12,2022,22.000000,-5.0
961,962,WC-2022,2022 FIFA World Cup,M-2022-62,France v Morocco,France,Morocco,semi-finals,not applicable,0,...,3.0,11.0,2022,1160.0,310.0,14,12,2022,22.000000,-8.0
962,963,WC-2022,2022 FIFA World Cup,M-2022-63,Croatia v Morocco,Croatia,Morocco,third-place match,not applicable,0,...,7.0,11.0,2022,325.0,310.0,17,12,2022,18.000000,-4.0
963,964,WC-2022,2022 FIFA World Cup,M-2022-64,Argentina v France,Argentina,France,final,not applicable,0,...,2.0,3.0,2022,920.0,1160.0,18,12,2022,18.000000,-1.0

In [506]:
df["Team value difference"]=(df["Home Team Squad Value (€M)"]-df["Away Team Squad Value (€M)"])
#df["Away Team value advantage"]=(df["Away Team Squad Value (€M)"]>df["Home Team Squad Value (€M)"]).astype(int)
df.tail()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,Away Team FIFA Rank,Year,Home Team Squad Value (€M),Away Team Squad Value (€M),match_day,match_month,match_year,start_time,Rank difference,Team value difference
959,960,WC-2022,2022 FIFA World Cup,M-2022-60,England v France,England,France,quarter-finals,not applicable,0,...,3.0,2022,1090.0,1160.0,10,12,2022,22.0,2.0,-70.0
960,961,WC-2022,2022 FIFA World Cup,M-2022-61,Argentina v Croatia,Argentina,Croatia,semi-finals,not applicable,0,...,7.0,2022,920.0,325.0,13,12,2022,22.0,-5.0,595.0
961,962,WC-2022,2022 FIFA World Cup,M-2022-62,France v Morocco,France,Morocco,semi-finals,not applicable,0,...,11.0,2022,1160.0,310.0,14,12,2022,22.0,-8.0,850.0
962,963,WC-2022,2022 FIFA World Cup,M-2022-63,Croatia v Morocco,Croatia,Morocco,third-place match,not applicable,0,...,11.0,2022,325.0,310.0,17,12,2022,18.0,-4.0,15.0
963,964,WC-2022,2022 FIFA World Cup,M-2022-64,Argentina v France,Argentina,France,final,not applicable,0,...,3.0,2022,920.0,1160.0,18,12,2022,18.0,-1.0,-240.0

In [507]:
y=df[["Result"]]
df.drop(columns=["Key Id", "Tournament Id","Group Name","tournament Name", "Match Id","Year", "Match Name","Result",'Home Team Id','Home Team Code', 'Away Team Id','Away Team Code','Country Name', 'Stadium Name','City Name','Score', 'Score Penalties','Result', 'Score', 'Home Team Score', 'Away Team Score','Home Team Score Margin', 'Away Team Score Margin', 'Extra Time','Penalty Shootout', 'Score Penalties', 'Home Team Score Penalties','Away Team Score Penalties', 'Result', 'Home Team Win', 'Away Team Win','Draw','Stadium Id'], inplace=True)

In [508]:
df

,Team 1,Team 2,Stage Name,Group Stage,Knockout Stage,Replayed,Replay,Home Team Name,Away Team Name,Home Team FIFA Rank,Away Team FIFA Rank,Home Team Squad Value (€M),Away Team Squad Value (€M),match_day,match_month,match_year,start_time,Rank difference,Team value difference
0,France,Mexico,group stage,1,0,0,0,France,Mexico,6.0,20.0,1.5,0.5,13,7,1930,15.000000,-14.0,1.0
1,United States,Belgium,group stage,1,0,0,0,United States,Belgium,10.0,8.0,0.9,1.1,13,7,1930,15.000000,2.0,-0.2
2,Yugoslavia,Brazil,group stage,1,0,0,0,Yugoslavia,Brazil,4.0,5.0,1.8,1.6,14,7,1930,12.750000,-1.0,0.2
3,Romania,Peru,group stage,1,0,0,0,Romania,Peru,14.0,18.0,0.9,0.7,14,7,1930,14.833333,-4.0,0.2
4,Argentina,France,group stage,1,0,0,0,Argentina,France,2.0,6.0,2.2,1.5,15,7,1930,16.000000,-4.0,0.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,England,France,quarter-finals,0,1,0,0,England,France,5.0,3.0,1090.0,1160.0,10,12,2022,22.000000,2.0,-70.0
960,Argentina,Croatia,semi-finals,0,1,0,0,Argentina,Croatia,2.0,7.0,920.0,325.0,13,12,2022,22.000000,-5.0,595.0
961,France,Morocco,semi-finals,0,1,0,0,France,Morocco,3.0,11.0,1160.0,310.0,14,12,2022,22.000000,-8.0,850.0
962,Croatia,Morocco,third-place match,0,1,0,0,Croatia,Morocco,7.0,11.0,325.0,310.0,17,12,2022,18.000000,-4.0,15.0
963,Argentina,France,final,0,1,0,0,Argentina,France,2.0,3.0,920.0,1160.0,18,12,2022,18.000000,-1.0,-240.0

In [509]:
#categorical =x.select_dtypes(include="object").columns
categorical=[col for col in df.columns if df[col].dtype=="object"]
categorical

['Team 1', 'Team 2', 'Stage Name', 'Home Team Name', 'Away Team Name']

In [510]:
#chi2-square test
related_columns={}
not_related_columns={}

for col in categorical:
    table=pd.crosstab(df[col],y["Result"])
    chi2,p,dof,expected=chi2_contingency(table)
    if p>=0.05:
        not_related_columns[col]=p
    else:
        related_columns[col]=p

print("related_columns",related_columns)
print("\n not_related_columns",not_related_columns)

related_columns {'Team 1': np.float64(2.8924492152421955e-11), 'Team 2': np.float64(0.012825406034170617), 'Stage Name': np.float64(3.9626824582397054e-10), 'Home Team Name': np.float64(2.8924492152421955e-11), 'Away Team Name': np.float64(0.012825406034170617)}

 not_related_columns {}

In [511]:
#annova_test
numeric_col=[col for col in df.columns if df[col].dtypes!="object"]
numeric_col

['Group Stage',
 'Knockout Stage',
 'Replayed',
 'Replay',
 'Home Team FIFA Rank',
 'Away Team FIFA Rank',
 'Home Team Squad Value (€M)',
 'Away Team Squad Value (€M)',
 'match_day',
 'match_month',
 'match_year',
 'start_time',
 'Rank difference',
 'Team value difference']

In [512]:
#annova_test
related_numeric_columns={}
not_related_numeric_columns={}
for col in numeric_col:
    Away=df[y["Result"]==0][col]
    Draw=df[y["Result"]==1][col]
    Home=df[y["Result"]==2][col]
    f_stats,p_value=f_oneway(Away,Draw,Home)
    if p_value>=0.05:
        not_related_numeric_columns[col]=p_value
    else:
        related_numeric_columns[col]=p_value

print("related_numeric_columns : ",related_numeric_columns)
print("not_related_numeric_columns : ",not_related_numeric_columns)

related_numeric_columns :  {'Group Stage': np.float64(nan), 'Knockout Stage': np.float64(nan), 'Replayed': np.float64(nan), 'Replay': np.float64(nan), 'Home Team FIFA Rank': np.float64(nan), 'Away Team FIFA Rank': np.float64(nan), 'Home Team Squad Value (€M)': np.float64(nan), 'Away Team Squad Value (€M)': np.float64(nan), 'match_day': np.float64(nan), 'match_month': np.float64(nan), 'match_year': np.float64(nan), 'start_time': np.float64(nan), 'Rank difference': np.float64(nan), 'Team value difference': np.float64(nan)}
not_related_numeric_columns :  {}

C:\Users\Abhishek k\AppData\Local\Temp\ipykernel_21508\3907210790.py:8: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  f_stats,p_value=f_oneway(Away,Draw,Home)

In [513]:
y

            Result
0    home team win
1    home team win
2    home team win
3    home team win
4    home team win
..             ...
959  away team win
960  home team win
961  home team win
962  home team win
963  home team win

[964 rows x 1 columns]

In [514]:
y["Result"]=y["Result"].map({"draw": 0,"away team win": 1,"home team win": 2 })
y

C:\Users\Abhishek k\AppData\Local\Temp\ipykernel_21508\1451611114.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["Result"]=y["Result"].map({"draw": 0,"away team win": 1,"home team win": 2 })

     Result
0         2
1         2
2         2
3         2
4         2
..      ...
959       1
960       2
961       2
962       2
963       2

[964 rows x 1 columns]

In [515]:
df["Stage Name"].unique()

array(['group stage', 'semi-finals', 'final', 'round of 16',
       'quarter-finals', 'third-place match', 'final round',
       'second group stage'], dtype=object)

In [516]:
df["Stage Name"]=df["Stage Name"].map({"group stage":0,"second group stage":0, "round of 32":1, "round of 16":2, "quarter-finals":3, "semi-finals":4,"third-place match":4, "final round":5,"final":5})
df.tail()

,Team 1,Team 2,Stage Name,Group Stage,Knockout Stage,Replayed,Replay,Home Team Name,Away Team Name,Home Team FIFA Rank,Away Team FIFA Rank,Home Team Squad Value (€M),Away Team Squad Value (€M),match_day,match_month,match_year,start_time,Rank difference,Team value difference
959,England,France,3,0,1,0,0,England,France,5.0,3.0,1090.0,1160.0,10,12,2022,22.0,2.0,-70.0
960,Argentina,Croatia,4,0,1,0,0,Argentina,Croatia,2.0,7.0,920.0,325.0,13,12,2022,22.0,-5.0,595.0
961,France,Morocco,4,0,1,0,0,France,Morocco,3.0,11.0,1160.0,310.0,14,12,2022,22.0,-8.0,850.0
962,Croatia,Morocco,4,0,1,0,0,Croatia,Morocco,7.0,11.0,325.0,310.0,17,12,2022,18.0,-4.0,15.0
963,Argentina,France,5,0,1,0,0,Argentina,France,2.0,3.0,920.0,1160.0,18,12,2022,18.0,-1.0,-240.0

In [517]:
x_train,x_test,y_train,y_test=train_test_split(df,y,test_size=0.2,random_state=42,stratify=y)
x_train

,Team 1,Team 2,Stage Name,Group Stage,Knockout Stage,Replayed,Replay,Home Team Name,Away Team Name,Home Team FIFA Rank,Away Team FIFA Rank,Home Team Squad Value (€M),Away Team Squad Value (€M),match_day,match_month,match_year,start_time,Rank difference,Team value difference
616,Nigeria,England,0,1,0,0,0,Nigeria,England,29.0,7.0,65.0,360.0,12,6,2002,15.50,22.0,-295.0
642,South Korea,Turkey,4,0,1,0,0,South Korea,Turkey,40.0,9.0,50.0,95.0,29,6,2002,20.00,31.0,-45.0
831,Netherlands,Costa Rica,3,0,1,0,0,Netherlands,Costa Rica,5.0,16.0,580.0,60.0,5,7,2014,17.00,-11.0,520.0
531,Germany,United States,0,1,0,0,0,Germany,United States,3.0,22.0,310.0,55.0,15,6,1998,21.00,-19.0,255.0
914,Portugal,Ghana,0,1,0,0,0,Portugal,Ghana,9.0,58.0,870.0,120.0,24,11,2022,19.00,-49.0,750.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,Argentina,South Korea,0,1,0,0,0,Argentina,South Korea,1.0,28.0,35.0,4.0,2,6,1986,12.00,-27.0,31.0
404,Brazil,France,3,0,1,0,0,Brazil,France,5.0,3.0,30.0,28.0,21,6,1986,12.00,2.0,2.0
415,Italy,Austria,0,1,0,0,0,Italy,Austria,3.0,16.0,50.0,10.0,9,6,1990,21.00,-13.0,40.0
309,Italy,Poland,0,1,0,0,0,Italy,Poland,1.0,3.0,30.0,12.0,14,6,1982,17.25,-2.0,18.0
494,Russia,Cameroon,0,1,0,0,0,Russia,Cameroon,13.0,31.0,70.0,45.0,28,6,1994,13.00,-18.0,25.0

In [518]:
#encoder = OneHotEncoder(sparse_output=False)
encoder=TargetEncoder(smooth="auto",cv=5,random_state=42)
for col in categorical:
    if col!='Stage Name':
        x_train[col]=encoder.fit_transform(x_train[[col]],y_train)
        x_test[col]=encoder.fit_transform(x_test[[col]],y_test)

In [519]:
parms={
    "objective":"multi:softmax",
    "num_class":3,
    "max_depth":4,
    "learning_rate":0.02,
    "n_estimators":100,
    "alpha":0.5
}
xgmodel = XGBClassifier(
    objective="multi:softmax",
    num_class=3,
    max_depth=6,
    learning_rate=0.01,
    n_estimators=300,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)
#xgmodel=XGBClassifier(**parms)
bagging=BaggingClassifier(xgmodel,n_estimators=10,random_state=42)
xgmodel.fit(x_train,y_train)
y_pred=xgmodel.predict(x_test)
print(classification_report(y_test,y_pred)) 
print(confusion_matrix(y_test,y_pred))
#bagging.fit(x_train,y_train)
#y_pred_bagging=bagging.predict(x_test)
#print(classification_report(y_test,y_pred_bagging))
#print(confusion_matrix(y_test,y_pred_bagging))

              precision    recall  f1-score   support

           0       0.40      0.11      0.17        36
           1       0.63      0.69      0.66        48
           2       0.75      0.90      0.82       109

    accuracy                           0.70       193
   macro avg       0.59      0.57      0.55       193
weighted avg       0.65      0.70      0.66       193

[[ 4 10 22]
 [ 4 33 11]
 [ 2  9 98]]