**PREPROCESSING**

In [542]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import chi2_contingency
from scipy.stats import f_oneway

from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [543]:
df = pd.read_csv("C:\\Users\\Abhishek k\\OneDrive\\Documents\\projects\\mini project ml\\Dataset\\dataset_final1.csv")

In [544]:
df.head()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,Away Team Score Penalties,Result,Home Team Win,Away Team Win,Draw,Home Team FIFA Rank,Away Team FIFA Rank,Year,Home Team Squad Value (€M),Away Team Squad Value (€M)
0,1,WC-1930,1930 FIFA World Cup,M-1930-01,France v Mexico,France,Mexico,group stage,Group 1,1,...,0,home team win,1,0,0,6.0,20.0,1930,1.5,0.5
1,2,WC-1930,1930 FIFA World Cup,M-1930-02,United States v Belgium,United States,Belgium,group stage,Group 4,1,...,0,home team win,1,0,0,10.0,8.0,1930,0.9,1.1
2,3,WC-1930,1930 FIFA World Cup,M-1930-03,Yugoslavia v Brazil,Yugoslavia,Brazil,group stage,Group 2,1,...,0,home team win,1,0,0,4.0,5.0,1930,1.8,1.6
3,4,WC-1930,1930 FIFA World Cup,M-1930-04,Romania v Peru,Romania,Peru,group stage,Group 3,1,...,0,home team win,1,0,0,14.0,18.0,1930,0.9,0.7
4,5,WC-1930,1930 FIFA World Cup,M-1930-05,Argentina v France,Argentina,France,group stage,Group 1,1,...,0,home team win,1,0,0,2.0,6.0,1930,2.2,1.5

In [545]:
df.shape

(964, 44)

In [546]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 44 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Key Id                      964 non-null    int64
 1   Tournament Id               964 non-null    object
 2   tournament Name             964 non-null    object
 3   Match Id                    964 non-null    object
 4   Match Name                  964 non-null    object
 5   Team 1                      964 non-null    object
 6   Team 2                      964 non-null    object
 7   Stage Name                  964 non-null    object
 8   Group Name                  964 non-null    object
 9   Group Stage                 964 non-null    int64
 10  Knockout Stage              964 non-null    int64
 11  Replayed                    964 non-null    int64
 12  Replay                      964 non-null    int64
 13  Match Date                  964 non-null    object
 14  Match Time                  964 non-null    object
 15  Stadium Id                  964 non-null    object
 16  Stadium Name                964 non-null    object
 17  City Name                   964 non-null    object
 18  Country Name                964 non-null    object
 19  Home Team Id                964 non-null    object
 20  Home Team Name              964 non-null    object
 21  Home Team Code              964 non-null    object
 22  Away Team Id                964 non-null    object
 23  Away Team Name              964 non-null    object
 24  Away Team Code              964 non-null    object
 25  Score                       964 non-null    object
 26  Home Team Score             964 non-null    int64
 27  Away Team Score             964 non-null    int64
 28  Home Team Score Margin      964 non-null    int64
 29  Away Team Score Margin      964 non-null    int64
 30  Extra Time                  964 non-null    int64
 31  Penalty Shootout            964 non-null    int64
 32  Score Penalties             964 non-null    object
 33  Home Team Score Penalties   964 non-null    int64
 34  Away Team Score Penalties   964 non-null    int64
 35  Result                      964 non-null    object
 36  Home Team Win               964 non-null    int64
 37  Away Team Win               964 non-null    int64
 38  Draw                        964 non-null    int64
 39  Home Team FIFA Rank         964 non-null    float64
 40  Away Team FIFA Rank         964 non-null    float64
 41  Year                        964 non-null    int64
 42  Home Team Squad Value (€M)  964 non-null    float64
 43  Away Team Squad Value (€M)  964 non-null    float64
dtypes: float64(4), int64(17), object(23)
memory usage: 331.5+ KB

In [547]:
df.describe()

,Key Id,Group Stage,Knockout Stage,Replayed,Replay,Home Team Score,Away Team Score,Home Team Score Margin,Away Team Score Margin,Extra Time,...,Home Team Score Penalties,Away Team Score Penalties,Home Team Win,Away Team Win,Draw,Home Team FIFA Rank,Away Team FIFA Rank,Year,Home Team Squad Value (€M),Away Team Squad Value (€M)
count,964.00000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,...,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000
mean,482.50000,0.744813,0.255187,0.004149,0.004149,1.766598,1.054979,0.711618,-0.711618,0.075726,...,0.121369,0.108921,0.565353,0.248963,0.185685,12.942946,17.575726,1989.244813,163.653734,121.178527
std,278.42713,0.436192,0.436192,0.064315,0.064315,1.601040,1.071720,1.925893,1.925893,0.264697,...,0.665731,0.600764,0.495968,0.432637,0.389054,15.123166,15.648710,24.014409,244.252693,204.221371
min,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-7.000000,-9.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1930.000000,0.400000,0.300000
25%,241.75000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,-2.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,6.000000,1974.000000,8.000000,5.000000
50%,482.50000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,-1.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,7.000000,13.000000,1994.000000,41.000000,35.000000
75%,723.25000,1.000000,1.000000,0.000000,0.000000,3.000000,2.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,16.000000,25.000000,2010.000000,210.000000,125.000000
max,964.00000,1.000000,1.000000,1.000000,1.000000,10.000000,7.000000,9.000000,7.000000,1.000000,...,5.000000,5.000000,1.000000,1.000000,1.000000,105.000000,105.000000,2022.000000,1160.000000,1160.000000

In [548]:
df.isna().sum()

Key Id                        0
Tournament Id                 0
tournament Name               0
Match Id                      0
Match Name                    0
Team 1                        0
Team 2                        0
Stage Name                    0
Group Name                    0
Group Stage                   0
Knockout Stage                0
Replayed                      0
Replay                        0
Match Date                    0
Match Time                    0
Stadium Id                    0
Stadium Name                  0
City Name                     0
Country Name                  0
Home Team Id                  0
Home Team Name                0
Home Team Code                0
Away Team Id                  0
Away Team Name                0
Away Team Code                0
Score                         0
Home Team Score               0
Away Team Score               0
Home Team Score Margin        0
Away Team Score Margin        0
Extra Time                    0
Penalty Shootout              0
Score Penalties               0
Home Team Score Penalties     0
Away Team Score Penalties     0
Result                        0
Home Team Win                 0
Away Team Win                 0
Draw                          0
Home Team FIFA Rank           0
Away Team FIFA Rank           0
Year                          0
Home Team Squad Value (€M)    0
Away Team Squad Value (€M)    0
dtype: int64

In [549]:
df.columns

Index(['Key Id', 'Tournament Id', 'tournament Name', 'Match Id', 'Match Name',
       'Team 1', 'Team 2', 'Stage Name', 'Group Name', 'Group Stage',
       'Knockout Stage', 'Replayed', 'Replay', 'Match Date', 'Match Time',
       'Stadium Id', 'Stadium Name', 'City Name', 'Country Name',
       'Home Team Id', 'Home Team Name', 'Home Team Code', 'Away Team Id',
       'Away Team Name', 'Away Team Code', 'Score', 'Home Team Score',
       'Away Team Score', 'Home Team Score Margin', 'Away Team Score Margin',
       'Extra Time', 'Penalty Shootout', 'Score Penalties',
       'Home Team Score Penalties', 'Away Team Score Penalties', 'Result',
       'Home Team Win', 'Away Team Win', 'Draw', 'Home Team FIFA Rank',
       'Away Team FIFA Rank', 'Year', 'Home Team Squad Value (€M)',
       'Away Team Squad Value (€M)'],
      dtype='object')

In [550]:
#df["Match Date"].dtype
df["Match Date"]=pd.to_datetime(df['Match Date'],format="mixed")
df["match_day"]=df["Match Date"].dt.day
df["match_month"]=df["Match Date"].dt.month
df["match_year"]=df["Match Date"].dt.year
df.drop("Match Date",axis=1,inplace=True)
df.head()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,Away Team Win,Draw,Home Team FIFA Rank,Away Team FIFA Rank,Year,Home Team Squad Value (€M),Away Team Squad Value (€M),match_day,match_month,match_year
0,1,WC-1930,1930 FIFA World Cup,M-1930-01,France v Mexico,France,Mexico,group stage,Group 1,1,...,0,0,6.0,20.0,1930,1.5,0.5,13,7,1930
1,2,WC-1930,1930 FIFA World Cup,M-1930-02,United States v Belgium,United States,Belgium,group stage,Group 4,1,...,0,0,10.0,8.0,1930,0.9,1.1,13,7,1930
2,3,WC-1930,1930 FIFA World Cup,M-1930-03,Yugoslavia v Brazil,Yugoslavia,Brazil,group stage,Group 2,1,...,0,0,4.0,5.0,1930,1.8,1.6,14,7,1930
3,4,WC-1930,1930 FIFA World Cup,M-1930-04,Romania v Peru,Romania,Peru,group stage,Group 3,1,...,0,0,14.0,18.0,1930,0.9,0.7,14,7,1930
4,5,WC-1930,1930 FIFA World Cup,M-1930-05,Argentina v France,Argentina,France,group stage,Group 1,1,...,0,0,2.0,6.0,1930,2.2,1.5,15,7,1930

In [551]:
df.drop(["Year"],axis=1,inplace=True )
df.head()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,Home Team Win,Away Team Win,Draw,Home Team FIFA Rank,Away Team FIFA Rank,Home Team Squad Value (€M),Away Team Squad Value (€M),match_day,match_month,match_year
0,1,WC-1930,1930 FIFA World Cup,M-1930-01,France v Mexico,France,Mexico,group stage,Group 1,1,...,1,0,0,6.0,20.0,1.5,0.5,13,7,1930
1,2,WC-1930,1930 FIFA World Cup,M-1930-02,United States v Belgium,United States,Belgium,group stage,Group 4,1,...,1,0,0,10.0,8.0,0.9,1.1,13,7,1930
2,3,WC-1930,1930 FIFA World Cup,M-1930-03,Yugoslavia v Brazil,Yugoslavia,Brazil,group stage,Group 2,1,...,1,0,0,4.0,5.0,1.8,1.6,14,7,1930
3,4,WC-1930,1930 FIFA World Cup,M-1930-04,Romania v Peru,Romania,Peru,group stage,Group 3,1,...,1,0,0,14.0,18.0,0.9,0.7,14,7,1930
4,5,WC-1930,1930 FIFA World Cup,M-1930-05,Argentina v France,Argentina,France,group stage,Group 1,1,...,1,0,0,2.0,6.0,2.2,1.5,15,7,1930

In [552]:
df["Match Time"]=pd.to_datetime(df["Match Time"],format="mixed")
df["start_time"]=(df["Match Time"].dt.hour+(df["Match Time"].dt.minute)/60)
df.drop("Match Time",axis=1,inplace=True)

In [553]:
df.drop(columns=["Key Id", "Tournament Id", "tournament Name", "Match Id", "Match Name"],inplace=True)
df

,Team 1,Team 2,Stage Name,Group Name,Group Stage,Knockout Stage,Replayed,Replay,Stadium Id,Stadium Name,...,Away Team Win,Draw,Home Team FIFA Rank,Away Team FIFA Rank,Home Team Squad Value (€M),Away Team Squad Value (€M),match_day,match_month,match_year,start_time
0,France,Mexico,group stage,Group 1,1,0,0,0,S-193,Estadio Pocitos,...,0,0,6.0,20.0,1.5,0.5,13,7,1930,15.000000
1,United States,Belgium,group stage,Group 4,1,0,0,0,S-192,Estadio Gran Parque Central,...,0,0,10.0,8.0,0.9,1.1,13,7,1930,15.000000
2,Yugoslavia,Brazil,group stage,Group 2,1,0,0,0,S-192,Estadio Gran Parque Central,...,0,0,4.0,5.0,1.8,1.6,14,7,1930,12.750000
3,Romania,Peru,group stage,Group 3,1,0,0,0,S-193,Estadio Pocitos,...,0,0,14.0,18.0,0.9,0.7,14,7,1930,14.833333
4,Argentina,France,group stage,Group 1,1,0,0,0,S-192,Estadio Gran Parque Central,...,0,0,2.0,6.0,2.2,1.5,15,7,1930,16.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,England,France,quarter-finals,not applicable,0,1,0,0,S-107,Al Bayt Stadium,...,1,0,5.0,3.0,1090.0,1160.0,10,12,2022,22.000000
960,Argentina,Croatia,semi-finals,not applicable,0,1,0,0,S-114,Lusail Stadium,...,0,0,2.0,7.0,920.0,325.0,13,12,2022,22.000000
961,France,Morocco,semi-finals,not applicable,0,1,0,0,S-107,Al Bayt Stadium,...,0,0,3.0,11.0,1160.0,310.0,14,12,2022,22.000000
962,Croatia,Morocco,third-place match,not applicable,0,1,0,0,S-110,Khalifa International Stadium,...,0,0,7.0,11.0,325.0,310.0,17,12,2022,18.000000
963,Argentina,France,final,not applicable,0,1,0,0,S-114,Lusail Stadium,...,0,0,2.0,3.0,920.0,1160.0,18,12,2022,18.000000

In [554]:
df.columns

Index(['Team 1', 'Team 2', 'Stage Name', 'Group Name', 'Group Stage',
       'Knockout Stage', 'Replayed', 'Replay', 'Stadium Id', 'Stadium Name',
       'City Name', 'Country Name', 'Home Team Id', 'Home Team Name',
       'Home Team Code', 'Away Team Id', 'Away Team Name', 'Away Team Code',
       'Score', 'Home Team Score', 'Away Team Score', 'Home Team Score Margin',
       'Away Team Score Margin', 'Extra Time', 'Penalty Shootout',
       'Score Penalties', 'Home Team Score Penalties',
       'Away Team Score Penalties', 'Result', 'Home Team Win', 'Away Team Win',
       'Draw', 'Home Team FIFA Rank', 'Away Team FIFA Rank',
       'Home Team Squad Value (€M)', 'Away Team Squad Value (€M)', 'match_day',
       'match_month', 'match_year', 'start_time'],
      dtype='object')

In [555]:
x=df.drop(columns=['Home Team Id','Home Team Code', 'Away Team Id','Away Team Code', 'Score', 'Score Penalties','Result', 'Score', 'Home Team Score', 'Away Team Score','Home Team Score Margin', 'Away Team Score Margin', 'Extra Time','Penalty Shootout', 'Score Penalties', 'Home Team Score Penalties','Away Team Score Penalties', 'Result', 'Home Team Win', 'Away Team Win','Draw','Stadium Id'])
y=df[["Result"]]
x.shape

(964, 21)

In [556]:
x.columns
x

,Team 1,Team 2,Stage Name,Group Name,Group Stage,Knockout Stage,Replayed,Replay,Stadium Name,City Name,...,Home Team Name,Away Team Name,Home Team FIFA Rank,Away Team FIFA Rank,Home Team Squad Value (€M),Away Team Squad Value (€M),match_day,match_month,match_year,start_time
0,France,Mexico,group stage,Group 1,1,0,0,0,Estadio Pocitos,Montevideo,...,France,Mexico,6.0,20.0,1.5,0.5,13,7,1930,15.000000
1,United States,Belgium,group stage,Group 4,1,0,0,0,Estadio Gran Parque Central,Montevideo,...,United States,Belgium,10.0,8.0,0.9,1.1,13,7,1930,15.000000
2,Yugoslavia,Brazil,group stage,Group 2,1,0,0,0,Estadio Gran Parque Central,Montevideo,...,Yugoslavia,Brazil,4.0,5.0,1.8,1.6,14,7,1930,12.750000
3,Romania,Peru,group stage,Group 3,1,0,0,0,Estadio Pocitos,Montevideo,...,Romania,Peru,14.0,18.0,0.9,0.7,14,7,1930,14.833333
4,Argentina,France,group stage,Group 1,1,0,0,0,Estadio Gran Parque Central,Montevideo,...,Argentina,France,2.0,6.0,2.2,1.5,15,7,1930,16.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,England,France,quarter-finals,not applicable,0,1,0,0,Al Bayt Stadium,Al Khor,...,England,France,5.0,3.0,1090.0,1160.0,10,12,2022,22.000000
960,Argentina,Croatia,semi-finals,not applicable,0,1,0,0,Lusail Stadium,Lusail,...,Argentina,Croatia,2.0,7.0,920.0,325.0,13,12,2022,22.000000
961,France,Morocco,semi-finals,not applicable,0,1,0,0,Al Bayt Stadium,Al Khor,...,France,Morocco,3.0,11.0,1160.0,310.0,14,12,2022,22.000000
962,Croatia,Morocco,third-place match,not applicable,0,1,0,0,Khalifa International Stadium,Al Rayyan,...,Croatia,Morocco,7.0,11.0,325.0,310.0,17,12,2022,18.000000
963,Argentina,France,final,not applicable,0,1,0,0,Lusail Stadium,Lusail,...,Argentina,France,2.0,3.0,920.0,1160.0,18,12,2022,18.000000

In [557]:
#categorical =x.select_dtypes(include="object").columns
categorical=[col for col in x.columns if x[col].dtype=="object"]
categorical

['Team 1',
 'Team 2',
 'Stage Name',
 'Group Name',
 'Stadium Name',
 'City Name',
 'Country Name',
 'Home Team Name',
 'Away Team Name']

In [558]:
#chi2-square test
related_columns={}
not_related_columns={}
for col in categorical:
    table=pd.crosstab(x[col],y["Result"])
    chi2,p,dof,expected=chi2_contingency(table)
    if p>=0.05:
        not_related_columns[col]=p
    else:
        related_columns[col]=p

print("related_columns",related_columns)
print("\n not_related_columns",not_related_columns)

related_columns {'Team 1': np.float64(2.8924492152421955e-11), 'Team 2': np.float64(0.012825406034170617), 'Stage Name': np.float64(3.9626824582397054e-10), 'Group Name': np.float64(1.1660024312766296e-19), 'City Name': np.float64(0.009022514559256904), 'Country Name': np.float64(3.8886617234225767e-10), 'Home Team Name': np.float64(2.8924492152421955e-11), 'Away Team Name': np.float64(0.012825406034170617)}

 not_related_columns {'Stadium Name': np.float64(0.056993019488706574)}

In [559]:
#annova_test
numeric_col=[col for col in x.columns if x[col].dtypes!="object"]
numeric_col

['Group Stage',
 'Knockout Stage',
 'Replayed',
 'Replay',
 'Home Team FIFA Rank',
 'Away Team FIFA Rank',
 'Home Team Squad Value (€M)',
 'Away Team Squad Value (€M)',
 'match_day',
 'match_month',
 'match_year',
 'start_time']

In [560]:
#annova_test
related_numeric_columns={}
not_related_numeric_columns={}
for col in numeric_col:
    Away=x[y["Result"]==0][col]
    Draw=x[y["Result"]==1][col]
    Home=x[y["Result"]==2][col]
    f_stats,p_value=f_oneway(Away,Draw,Home)
    if p_value>=0.05:
        not_related_numeric_columns[col]=p_value
    else:
        related_numeric_columns[col]=p_value

print("related_numeric_columns : ",related_numeric_columns)
print("not_related_numeric_columns : ",not_related_numeric_columns)

related_numeric_columns :  {'Group Stage': np.float64(nan), 'Knockout Stage': np.float64(nan), 'Replayed': np.float64(nan), 'Replay': np.float64(nan), 'Home Team FIFA Rank': np.float64(nan), 'Away Team FIFA Rank': np.float64(nan), 'Home Team Squad Value (€M)': np.float64(nan), 'Away Team Squad Value (€M)': np.float64(nan), 'match_day': np.float64(nan), 'match_month': np.float64(nan), 'match_year': np.float64(nan), 'start_time': np.float64(nan)}
not_related_numeric_columns :  {}

C:\Users\Abhishek k\AppData\Local\Temp\ipykernel_11732\2778953652.py:8: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  f_stats,p_value=f_oneway(Away,Draw,Home)

In [561]:
x.drop(["Stadium Name"],axis=1,inplace=True)
x.head()

,Team 1,Team 2,Stage Name,Group Name,Group Stage,Knockout Stage,Replayed,Replay,City Name,Country Name,Home Team Name,Away Team Name,Home Team FIFA Rank,Away Team FIFA Rank,Home Team Squad Value (€M),Away Team Squad Value (€M),match_day,match_month,match_year,start_time
0,France,Mexico,group stage,Group 1,1,0,0,0,Montevideo,Uruguay,France,Mexico,6.0,20.0,1.5,0.5,13,7,1930,15.000000
1,United States,Belgium,group stage,Group 4,1,0,0,0,Montevideo,Uruguay,United States,Belgium,10.0,8.0,0.9,1.1,13,7,1930,15.000000
2,Yugoslavia,Brazil,group stage,Group 2,1,0,0,0,Montevideo,Uruguay,Yugoslavia,Brazil,4.0,5.0,1.8,1.6,14,7,1930,12.750000
3,Romania,Peru,group stage,Group 3,1,0,0,0,Montevideo,Uruguay,Romania,Peru,14.0,18.0,0.9,0.7,14,7,1930,14.833333
4,Argentina,France,group stage,Group 1,1,0,0,0,Montevideo,Uruguay,Argentina,France,2.0,6.0,2.2,1.5,15,7,1930,16.000000

In [562]:
label_encoder = LabelEncoder()

In [564]:
columns_to_encode = [col for col in x.columns if x[col].dtype == "object"]
for col in columns_to_encode:
    x[col] = label_encoder.fit_transform(x[col])
y["Result"]=label_encoder.fit_transform(y["Result"])
x.head()

C:\Users\Abhishek k\AppData\Local\Temp\ipykernel_11732\3673683797.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["Result"]=label_encoder.fit_transform(y["Result"])

,Team 1,Team 2,Stage Name,Group Name,Group Stage,Knockout Stage,Replayed,Replay,City Name,Country Name,Home Team Name,Away Team Name,Home Team FIFA Rank,Away Team FIFA Rank,Home Team Squad Value (€M),Away Team Squad Value (€M),match_day,match_month,match_year,start_time
0,25,43,2,0,1,0,0,0,87,17,25,43,6.0,20.0,1.5,0.5,13,7,1930,15.000000
1,75,5,2,3,1,0,0,0,87,17,75,5,10.0,8.0,0.9,1.1,13,7,1930,15.000000
2,79,8,2,1,1,0,0,0,87,17,79,8,4.0,5.0,1.8,1.6,14,7,1930,12.750000
3,54,53,2,2,1,0,0,0,87,17,54,53,14.0,18.0,0.9,0.7,14,7,1930,14.833333
4,2,27,2,0,1,0,0,0,87,17,2,27,2.0,6.0,2.2,1.5,15,7,1930,16.000000

In [565]:
model = LogisticRegression()
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=42, test_size=0.2)
model

LogisticRegression()

In [566]:
model.fit(x_train,y_train)
model

c:\Users\Abhishek k\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Abhishek k\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [567]:
y_pred = model.predict(x_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.73      0.60      0.66        45
           1       0.50      0.02      0.04        47
           2       0.62      0.94      0.75       101

    accuracy                           0.64       193
   macro avg       0.62      0.52      0.48       193
weighted avg       0.61      0.64      0.55       193

[[27  0 18]
 [ 5  1 41]
 [ 5  1 95]]